services:
  profile-search:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/db_profile_search
      - SPRING_DATASOURCE_USERNAME=profile_search_root
      - SPRING_DATASOURCE_PASSWORD=ProfileSearch!123
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:15.2
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: profile_search_root
      POSTGRES_PASSWORD: ProfileSearch!123
      POSTGRES_DB: db_profile_search
    ports:
      - "5432:5432"
