services:
  profile-search:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/profilSearch
      - SPRING_DATASOURCE_USERNAME=search_root
      - SPRING_DATASOURCE_PASSWORD=ProileSearch!123
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:15.2
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: search_root
      POSTGRES_PASSWORD: ProileSearch!123
      POSTGRES_DB: profilSearch
    ports:
      - "5432:5432"
